### ISSUE TITLE
Use lowercase in patternsToInclude and patternsToExclude

### ISSUE THREAD

**Issue by hmartos** [ekergy/tweemanager#11]
It should compare Strings in lowercase to check if tweet should be included or not.

For example. if configuration file have `patternsToExclude = ['el hormiguero']`, a tweet which text contains "El Hormiguero" is included.

**Comment by cperales** [comment]
Those comparisons are done not only in lowercase but also with stemming, by `textclean` function. In tools.py it can be seen:

```
           # checking patterns:
            if self.PATTERNSTOINCLUDE:
                logging.debug("PATTERNSTOINCLUDE")
                # result = False
                for pattern in self.PATTERNSTOINCLUDE:
                    if textclean(pattern) in self.tweetdata['text_clean']:
                        logging.debug("patternstoinclude {} found in tweet id: {}".format(pattern, self.tweetdata['id']))
                        result = True
```
