### ISSUE TITLE
Script tweemanager_listenerwatchdog.py

### ISSUE THREAD

**Issue by hmartos** [ekergy/tweemanager#15]
The script tweemanager_listenerwatchdog.py is not working on Windows.

The problem could be the duplicity of proceses when a listener starts in Windows.
It create a process for tweemanager with its pid and another process for python with a different pid.

**Comment by cperales** [comment]
Be careful! You should not use same API user in several listener. About streaming, official documentation [says](https://dev.twitter.com/streaming/overview/connecting):

> Disconnections
> Twitter will close a streaming connection for the following reasons:
> 
> A client establishes too many connections with the same credentials. When this occurs, the oldest connection will be terminated. This means you have to be careful not to run two reconnecting clients in parallel with the same credentials, or else they will take turns disconnecting each other.

However, I think 2 connections can be set up without problem, but I'm not sure how much listener could you keep open

**Comment by cperales** [comment]
I suggest group all the queries together and then, before insterting it in the database, distinguish among several text patterns.

For example, if we want to set up two listener, one for Real Madrid and another from FC Barça, we can joint the two queries. Before saving the tweets into the database, we can separate them between Real Madrid's ones and FC Barça's.

This may imply change a little the code, for allowing several text patterns. However, if just two listeners are needed, almost surely two listeners can be set up independently. More listeners can be a problem.
