### ISSUE TITLE
Alert words

### ISSUE THREAD

**Issue by hmartos** [ekergy/tweemanager#16]
Reporting is writing report with 'cleaned' alert words. I'll explain myself.

I have defined the following alertwords section in configuration file:
`alertwords = [ "HeTeRoCliTo", "españoles", "lógicamente"]`

Then, I have executed `tweemanager reporting -c test.cfg -o mongodb` and when I check Reports collection, alert words are written lke   "heteroclito", "espanoles", "logicamente".

It is great that it uses 'cleaned' words to count words in DB, but it should write this words in Reports collection as they were defined in configuration file.

**Comment by cperales** [comment]
Solved
