### ISSUE TITLE
Problemas con Python 2.7 y Python 3

### ISSUE THREAD

**Issue by cperales** [ekergy/tweemanager#4]
El paquete, al haberse empezado a desarrollar en Python 2.7, funciona bien en esta versión pero da error al usar Python 3 (el error está relacionado con el paquete docopt).

Sin embargo, cuando se importa a Mongo, el problema es el contrario, puesto que se empezó a desarrollar en Python 3. Se crea un campo nuevo, text_clean, a partir del campo text. Se remueven los acentos con el paquete unicodedata, que parece tener problemas con Python 2.7 (pero que funciona bien con Python 3)

**Comment by hmarrao** [comment]
creo que ya tenemos el paquete compatible con python 2 y 3
