### ISSUE TITLE
Error desconocido

### ISSUE THREAD

**Issue by cperales** [ekergy/tweemanager#6]
Hay veces que intento usar "importToMongo" y obtengo un error desconocido (no sale por pantalla el error dado).

```
$ python tweemanager importToMongo < verver.json 
Reading, processing and importing json documents to mongo
Using stdin to process json data. One json per line.
Note: for really large jsons, use pipes. ej: '< or |' .
Error in json:{u'contributors': None, u'truncated': False, u'text': ...}

```

¿A qué puede ser debido? Sería interesante que mostrase por pantalla algún código de error.

**Comment by guillemborrell** [comment]
Chicos, siempre es una mala idea ocultar el traceback. Incluso cuando hay una excepción.

Prueba con el cambio que he subido.

**Comment by hmarrao** [comment]
El problema es que la linea que estas procesando no es un json,

**Comment by cperales** [comment]
@hmarrao me enteré de ese problema básicamente porque puse 

```
        except Exception as e:
            print(e)
            print("Error in json:" + line)
        # except:
        #     raise
        #     break
    sys.exit(0)
```

En __main__.py. No he realizado _commit_ para comentarlo primero si puede ser positivo ese cambio.
